on:
  release:
    types:
      - published
  
jobs:
  build:
    runs-on: ${{ matrix.runs-on }}
    strategy:
      matrix:
        include:
          - architecture: x86_64
            platform: linux
            runs-on: ubuntu-latest
          - architecture: x86_64
            platform: macosx
            runs-on: macos-latest
          - architecture: x64
            platform: windows
            runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4

      - uses: xmake-io/github-action-setup-xmake@v1

      - run: |
          xmake repo -u -y

      - run: |
          xmake f -a ${{ matrix.architecture }} -m release -p ${{ matrix.platform }} -v -y

      - run: |
          xmake -v -y

      - uses: actions/upload-artifact@v4
        with:
          name: ${{ github.event.repository.name }}-${{ matrix.platform }}-${{ matrix.architecture }}-${{ github.sha }}
          path: build/${{ matrix.platform }}/${{ matrix.architecture }}/release/

  update-release-notes:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - id: extract-release-notes
        uses: ffurrer2/extract-release-notes@v2

      - uses: softprops/action-gh-release@v2
        with:
          body: |
            ${{ steps.extract-release-notes.outputs.release_notes }}

  upload-to-release:
    needs:
      - build
      - update-release-notes
    permissions:
      contents: write
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - architecture: x86_64
            platform: linux
          - architecture: x86_64
            platform: macosx
          - architecture: x64
            platform: windows
    steps:
      - uses: actions/checkout@v4

      - uses: actions/download-artifact@v4
        with:
          name: ${{ github.event.repository.name }}-${{ matrix.platform }}-${{ matrix.architecture }}-${{ github.sha }}
          path: artifact

      - run: |
          cp CHANGELOG.md LICENSE README.md artifact/

      - name: Pack artifact (Windows)
        if: matrix.platform == 'windows'
        run: |
          zip -r ../${{ github.event.repository.name }}-${{ matrix.platform }}-${{ matrix.architecture }}.zip *
        working-directory: artifact
  
      - name: Pack artifact (Others)
        if: matrix.platform != 'windows'
        run: |
          tar -czvf ../${{ github.event.repository.name }}-${{ matrix.platform }}-${{ matrix.architecture }}.tar.gz *
        working-directory: artifact

      - name: Upload artifact to release (Windows)
        if: matrix.platform == 'windows'
        uses: softprops/action-gh-release@v2
        with:
          files: |
            ${{ github.event.repository.name }}-${{ matrix.platform }}-${{ matrix.architecture }}.zip

      - name: Upload artifact to release (Others)
        if: matrix.platform != 'windows'
        uses: softprops/action-gh-release@v2
        with:
          files: |
            ${{ github.event.repository.name }}-${{ matrix.platform }}-${{ matrix.architecture }}.tar.gz
